services:
  # default configuration for services in *this* file
  _defaults:
    autowire: false      # Automatically injects dependencies in your services.
    autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.

  Gracious\AkeneoExtras\Command\PimMassDeleteAttributesCommand:
    arguments:
      - '@pim_catalog.repository.attribute'
      - '@pim_catalog.repository.channel'
      - '@akeneo.pim.structure.query.attribute_is_an_family_variant_axis'
      - '@pim_catalog.saver.attribute'
      - '@pim_catalog.remover.attribute'
    tags:
      - { name: 'console.command' }

  Gracious\AkeneoExtras\Command\PimMassDeleteProductsCommand:
    arguments:
      - '@pim_catalog.repository.product'
      - '@pim_catalog.remover.product'
      - '@akeneo_elasticsearch.client.product_and_product_model'
    tags:
      - { name: 'console.command' }

  Gracious\AkeneoExtras\Command\PimMassDeleteProductModelsCommand:
    arguments:
      - '@pim_catalog.repository.product_model'
      - '@pim_catalog.remover.product_model'
      - '@akeneo_elasticsearch.client.product_and_product_model'
    tags:
      - { name: 'console.command' }

  Gracious\AkeneoExtras\Command\PimMassDeleteFamiliesCommand:
    arguments:
      - '@pim_catalog.repository.family'
      - '@pim_catalog.remover.family'
    tags:
      - { name: 'console.command' }

  Gracious\AkeneoExtras\Command\PimMassDeleteFamilyVariantsCommand:
    arguments:
      - '@pim_catalog.repository.family_variant'
      - '@pim_catalog.remover.family_variant'
    tags:
      - { name: 'console.command' }

  Gracious\AkeneoExtras\Command\PimMassDeleteSystemFlushCommand:
    tags:
      - { name: 'console.command' }

  Gracious\AkeneoExtras\Command\AkeneoFileStoragePruneCatalogCommand:
    arguments:
      $mediaAttributeRepository: '@pim_catalog.repository.attribute'
      $productQueryBuilderFactory: '@pim_catalog.query.product_query_builder_factory_for_reading_purpose'
      $productModelQueryBuilderFactory: '@pim_catalog.query.product_model_query_builder_factory'
      $entityManager: '@doctrine.orm.entity_manager'
      $filesystemProvider: '@akeneo_file_storage.file_storage.filesystem_provider'
      $fileInfoRepository: '@akeneo_file_storage.repository.file_info'
      $fileRemover: '@akeneo_file_storage.remover.file'
      $filesystemAlias: 'catalogStorage'
    tags:
      - { name: 'console.command' }
